"""empty message

Revision ID: 4120b3958840
Revises: 394da626c1ac
Create Date: 2025-12-29 18:43:16.079923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4120b3958840'
down_revision: Union[str, Sequence[str], None] = '394da626c1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('temperature', sa.Integer(), nullable=False))
    op.drop_column('temperature', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('additional_info', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('temperature', 'temperature')
    # ### end Alembic commands ###
